### ISSUE TITLE
Create additional ansible tasks to create and populate the INITRD and VMLINUZ images

### ISSUE THREAD

**Issue by tmichett** [tmichett/PXEServer#4]
## Check for Files in PXEBoot Remix Directory to decide if to download new files

**Comment by tmichett** [comment]
```
## Obtain Boot images for PXEBoot
    - name: Download Boot Images for PXEBoot
      ansible.builtin.get_url:
        url:  https://download.fedoraproject.org/pub/fedora/linux/releases/{{ fedora_version }}/Server/x86_64/os/images/pxeboot/{{ item }}
        dest: /var/www/html/FedoraRemixPXE/
      loop: "{{ fedora_boot_files }}"
```

```
  vars:
    fedora_boot_files:
      - vmlinuz
      - initrd.img
```
